version: 2
jobs:
  build:
    working_directory: ~/csarko.sh
    docker:
      - image: csarko/node_terraform_awscli
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install dependencies
          command: npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: tests
          command: npm run test:ci
      - run:
          name: deploy web assets
          command: npm run build && aws s3 sync build s3://readme-viewer.csarko.sh --exclude data/* --exclude docs/*
      - run:
          name: deploy "server" lambda
          command: |
            cp build/index.html lambdas/server/
            cd lambdas/server/
            npm ci
            zip -r server.zip *
            aws s3 mv server.zip s3://readme-viewer.csarko.sh-lambdas2/
            aws --region us-east-1 lambda update-function-code --function-name readme-viewer --s3-bucket readme-viewer.csarko.sh-lambdas2 --s3-key server.zip
            cd ../..
      - run:
          name: deploy "cache-gh-data" lambda
          command: |
            cd lambdas/cache-gh-data
            npm ci
            zip -r cache-gh-data.zip *
            aws s3 mv cache-gh-data.zip s3://readme-viewer.csarko.sh-lambdas2/
            aws --region us-east-1 lambda update-function-code --function-name cache-gh-data --s3-bucket readme-viewer.csarko.sh-lambdas2 --s3-key cache-gh-data.zip
            cd ../..
